apiVersion: apps/v1
kind: Deployment
metadata:
  name: cap-
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: cstclair25/cap:latest
          ports:
            - name: http
              containerPort: 80